from tkinter import *
root = Tk()
root.title("Product Calculator")
root.geometry("300x200")
def product():
    a = int(num1.get())
    b = int(num2.get())
    result.config(text="Product = " + str(a * b))
Label(root, text="First Number").pack()
num1 = Entry(root)
num1.pack()
Label(root, text="Second Number").pack()
num2 = Entry(root)
num2.pack()
Button(root, text="Multiply", command=product).pack()
result = Label(root, text="")
result.pack()
root.mainloop()
